/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppTriageRouteImport } from './routes/_app.triage'
import { Route as AppSupervisorRouteImport } from './routes/_app.supervisor'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppReferralsRouteImport } from './routes/_app.referrals'
import { Route as AppPatientRouteImport } from './routes/_app.patient'
import { Route as AppNotificationsRouteImport } from './routes/_app.notifications'
import { Route as AppMaternalRouteImport } from './routes/_app.maternal'
import { Route as AppHelpRouteImport } from './routes/_app.help'
import { Route as AppFaqRouteImport } from './routes/_app.faq'
import { Route as AppDocumentRouteImport } from './routes/_app.document'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppConsultationsRouteImport } from './routes/_app.consultations'
import { Route as AppCalculatorRouteImport } from './routes/_app.calculator'
import { Route as AppAuditRouteImport } from './routes/_app.audit'
import { Route as AppPatientsIndexRouteImport } from './routes/_app.patients.index'
import { Route as AppPatientsBatchRegisterRouteImport } from './routes/_app.patients.batch-register'
import { Route as AppPatientsPatientIdRouteImport } from './routes/_app.patients.$patientId'
import { Route as AppPatientScanRouteImport } from './routes/_app.patient.scan'
import { Route as AppPatientRecordRouteImport } from './routes/_app.patient.record'
import { Route as AppPatientMedicationsRouteImport } from './routes/_app.patient.medications'
import { Route as AppDashboardCommunityRouteImport } from './routes/_app.dashboard.community'
import { Route as AppConsultationsRequestRouteImport } from './routes/_app.consultations.request'
import { Route as AppConsultationsIdRouteImport } from './routes/_app.consultations.$id'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppTriageRoute = AppTriageRouteImport.update({
  id: '/triage',
  path: '/triage',
  getParentRoute: () => AppRoute,
} as any)
const AppSupervisorRoute = AppSupervisorRouteImport.update({
  id: '/supervisor',
  path: '/supervisor',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppReferralsRoute = AppReferralsRouteImport.update({
  id: '/referrals',
  path: '/referrals',
  getParentRoute: () => AppRoute,
} as any)
const AppPatientRoute = AppPatientRouteImport.update({
  id: '/patient',
  path: '/patient',
  getParentRoute: () => AppRoute,
} as any)
const AppNotificationsRoute = AppNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AppRoute,
} as any)
const AppMaternalRoute = AppMaternalRouteImport.update({
  id: '/maternal',
  path: '/maternal',
  getParentRoute: () => AppRoute,
} as any)
const AppHelpRoute = AppHelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => AppRoute,
} as any)
const AppFaqRoute = AppFaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => AppRoute,
} as any)
const AppDocumentRoute = AppDocumentRouteImport.update({
  id: '/document',
  path: '/document',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppConsultationsRoute = AppConsultationsRouteImport.update({
  id: '/consultations',
  path: '/consultations',
  getParentRoute: () => AppRoute,
} as any)
const AppCalculatorRoute = AppCalculatorRouteImport.update({
  id: '/calculator',
  path: '/calculator',
  getParentRoute: () => AppRoute,
} as any)
const AppAuditRoute = AppAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AppRoute,
} as any)
const AppPatientsIndexRoute = AppPatientsIndexRouteImport.update({
  id: '/patients/',
  path: '/patients/',
  getParentRoute: () => AppRoute,
} as any)
const AppPatientsBatchRegisterRoute =
  AppPatientsBatchRegisterRouteImport.update({
    id: '/patients/batch-register',
    path: '/patients/batch-register',
    getParentRoute: () => AppRoute,
  } as any)
const AppPatientsPatientIdRoute = AppPatientsPatientIdRouteImport.update({
  id: '/patients/$patientId',
  path: '/patients/$patientId',
  getParentRoute: () => AppRoute,
} as any)
const AppPatientScanRoute = AppPatientScanRouteImport.update({
  id: '/scan',
  path: '/scan',
  getParentRoute: () => AppPatientRoute,
} as any)
const AppPatientRecordRoute = AppPatientRecordRouteImport.update({
  id: '/record',
  path: '/record',
  getParentRoute: () => AppPatientRoute,
} as any)
const AppPatientMedicationsRoute = AppPatientMedicationsRouteImport.update({
  id: '/medications',
  path: '/medications',
  getParentRoute: () => AppPatientRoute,
} as any)
const AppDashboardCommunityRoute = AppDashboardCommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => AppDashboardRoute,
} as any)
const AppConsultationsRequestRoute = AppConsultationsRequestRouteImport.update({
  id: '/request',
  path: '/request',
  getParentRoute: () => AppConsultationsRoute,
} as any)
const AppConsultationsIdRoute = AppConsultationsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppConsultationsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/audit': typeof AppAuditRoute
  '/calculator': typeof AppCalculatorRoute
  '/consultations': typeof AppConsultationsRouteWithChildren
  '/dashboard': typeof AppDashboardRouteWithChildren
  '/document': typeof AppDocumentRoute
  '/faq': typeof AppFaqRoute
  '/help': typeof AppHelpRoute
  '/maternal': typeof AppMaternalRoute
  '/notifications': typeof AppNotificationsRoute
  '/patient': typeof AppPatientRouteWithChildren
  '/referrals': typeof AppReferralsRoute
  '/settings': typeof AppSettingsRoute
  '/supervisor': typeof AppSupervisorRoute
  '/triage': typeof AppTriageRoute
  '/consultations/$id': typeof AppConsultationsIdRoute
  '/consultations/request': typeof AppConsultationsRequestRoute
  '/dashboard/community': typeof AppDashboardCommunityRoute
  '/patient/medications': typeof AppPatientMedicationsRoute
  '/patient/record': typeof AppPatientRecordRoute
  '/patient/scan': typeof AppPatientScanRoute
  '/patients/$patientId': typeof AppPatientsPatientIdRoute
  '/patients/batch-register': typeof AppPatientsBatchRegisterRoute
  '/patients/': typeof AppPatientsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/audit': typeof AppAuditRoute
  '/calculator': typeof AppCalculatorRoute
  '/consultations': typeof AppConsultationsRouteWithChildren
  '/dashboard': typeof AppDashboardRouteWithChildren
  '/document': typeof AppDocumentRoute
  '/faq': typeof AppFaqRoute
  '/help': typeof AppHelpRoute
  '/maternal': typeof AppMaternalRoute
  '/notifications': typeof AppNotificationsRoute
  '/patient': typeof AppPatientRouteWithChildren
  '/referrals': typeof AppReferralsRoute
  '/settings': typeof AppSettingsRoute
  '/supervisor': typeof AppSupervisorRoute
  '/triage': typeof AppTriageRoute
  '/consultations/$id': typeof AppConsultationsIdRoute
  '/consultations/request': typeof AppConsultationsRequestRoute
  '/dashboard/community': typeof AppDashboardCommunityRoute
  '/patient/medications': typeof AppPatientMedicationsRoute
  '/patient/record': typeof AppPatientRecordRoute
  '/patient/scan': typeof AppPatientScanRoute
  '/patients/$patientId': typeof AppPatientsPatientIdRoute
  '/patients/batch-register': typeof AppPatientsBatchRegisterRoute
  '/patients': typeof AppPatientsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/audit': typeof AppAuditRoute
  '/_app/calculator': typeof AppCalculatorRoute
  '/_app/consultations': typeof AppConsultationsRouteWithChildren
  '/_app/dashboard': typeof AppDashboardRouteWithChildren
  '/_app/document': typeof AppDocumentRoute
  '/_app/faq': typeof AppFaqRoute
  '/_app/help': typeof AppHelpRoute
  '/_app/maternal': typeof AppMaternalRoute
  '/_app/notifications': typeof AppNotificationsRoute
  '/_app/patient': typeof AppPatientRouteWithChildren
  '/_app/referrals': typeof AppReferralsRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/supervisor': typeof AppSupervisorRoute
  '/_app/triage': typeof AppTriageRoute
  '/_app/consultations/$id': typeof AppConsultationsIdRoute
  '/_app/consultations/request': typeof AppConsultationsRequestRoute
  '/_app/dashboard/community': typeof AppDashboardCommunityRoute
  '/_app/patient/medications': typeof AppPatientMedicationsRoute
  '/_app/patient/record': typeof AppPatientRecordRoute
  '/_app/patient/scan': typeof AppPatientScanRoute
  '/_app/patients/$patientId': typeof AppPatientsPatientIdRoute
  '/_app/patients/batch-register': typeof AppPatientsBatchRegisterRoute
  '/_app/patients/': typeof AppPatientsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/audit'
    | '/calculator'
    | '/consultations'
    | '/dashboard'
    | '/document'
    | '/faq'
    | '/help'
    | '/maternal'
    | '/notifications'
    | '/patient'
    | '/referrals'
    | '/settings'
    | '/supervisor'
    | '/triage'
    | '/consultations/$id'
    | '/consultations/request'
    | '/dashboard/community'
    | '/patient/medications'
    | '/patient/record'
    | '/patient/scan'
    | '/patients/$patientId'
    | '/patients/batch-register'
    | '/patients/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/audit'
    | '/calculator'
    | '/consultations'
    | '/dashboard'
    | '/document'
    | '/faq'
    | '/help'
    | '/maternal'
    | '/notifications'
    | '/patient'
    | '/referrals'
    | '/settings'
    | '/supervisor'
    | '/triage'
    | '/consultations/$id'
    | '/consultations/request'
    | '/dashboard/community'
    | '/patient/medications'
    | '/patient/record'
    | '/patient/scan'
    | '/patients/$patientId'
    | '/patients/batch-register'
    | '/patients'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/_app/audit'
    | '/_app/calculator'
    | '/_app/consultations'
    | '/_app/dashboard'
    | '/_app/document'
    | '/_app/faq'
    | '/_app/help'
    | '/_app/maternal'
    | '/_app/notifications'
    | '/_app/patient'
    | '/_app/referrals'
    | '/_app/settings'
    | '/_app/supervisor'
    | '/_app/triage'
    | '/_app/consultations/$id'
    | '/_app/consultations/request'
    | '/_app/dashboard/community'
    | '/_app/patient/medications'
    | '/_app/patient/record'
    | '/_app/patient/scan'
    | '/_app/patients/$patientId'
    | '/_app/patients/batch-register'
    | '/_app/patients/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/triage': {
      id: '/_app/triage'
      path: '/triage'
      fullPath: '/triage'
      preLoaderRoute: typeof AppTriageRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/supervisor': {
      id: '/_app/supervisor'
      path: '/supervisor'
      fullPath: '/supervisor'
      preLoaderRoute: typeof AppSupervisorRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/referrals': {
      id: '/_app/referrals'
      path: '/referrals'
      fullPath: '/referrals'
      preLoaderRoute: typeof AppReferralsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/patient': {
      id: '/_app/patient'
      path: '/patient'
      fullPath: '/patient'
      preLoaderRoute: typeof AppPatientRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/notifications': {
      id: '/_app/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AppNotificationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/maternal': {
      id: '/_app/maternal'
      path: '/maternal'
      fullPath: '/maternal'
      preLoaderRoute: typeof AppMaternalRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/help': {
      id: '/_app/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof AppHelpRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/faq': {
      id: '/_app/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof AppFaqRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/document': {
      id: '/_app/document'
      path: '/document'
      fullPath: '/document'
      preLoaderRoute: typeof AppDocumentRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/consultations': {
      id: '/_app/consultations'
      path: '/consultations'
      fullPath: '/consultations'
      preLoaderRoute: typeof AppConsultationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/calculator': {
      id: '/_app/calculator'
      path: '/calculator'
      fullPath: '/calculator'
      preLoaderRoute: typeof AppCalculatorRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/audit': {
      id: '/_app/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AppAuditRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/patients/': {
      id: '/_app/patients/'
      path: '/patients'
      fullPath: '/patients/'
      preLoaderRoute: typeof AppPatientsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/patients/batch-register': {
      id: '/_app/patients/batch-register'
      path: '/patients/batch-register'
      fullPath: '/patients/batch-register'
      preLoaderRoute: typeof AppPatientsBatchRegisterRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/patients/$patientId': {
      id: '/_app/patients/$patientId'
      path: '/patients/$patientId'
      fullPath: '/patients/$patientId'
      preLoaderRoute: typeof AppPatientsPatientIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/patient/scan': {
      id: '/_app/patient/scan'
      path: '/scan'
      fullPath: '/patient/scan'
      preLoaderRoute: typeof AppPatientScanRouteImport
      parentRoute: typeof AppPatientRoute
    }
    '/_app/patient/record': {
      id: '/_app/patient/record'
      path: '/record'
      fullPath: '/patient/record'
      preLoaderRoute: typeof AppPatientRecordRouteImport
      parentRoute: typeof AppPatientRoute
    }
    '/_app/patient/medications': {
      id: '/_app/patient/medications'
      path: '/medications'
      fullPath: '/patient/medications'
      preLoaderRoute: typeof AppPatientMedicationsRouteImport
      parentRoute: typeof AppPatientRoute
    }
    '/_app/dashboard/community': {
      id: '/_app/dashboard/community'
      path: '/community'
      fullPath: '/dashboard/community'
      preLoaderRoute: typeof AppDashboardCommunityRouteImport
      parentRoute: typeof AppDashboardRoute
    }
    '/_app/consultations/request': {
      id: '/_app/consultations/request'
      path: '/request'
      fullPath: '/consultations/request'
      preLoaderRoute: typeof AppConsultationsRequestRouteImport
      parentRoute: typeof AppConsultationsRoute
    }
    '/_app/consultations/$id': {
      id: '/_app/consultations/$id'
      path: '/$id'
      fullPath: '/consultations/$id'
      preLoaderRoute: typeof AppConsultationsIdRouteImport
      parentRoute: typeof AppConsultationsRoute
    }
  }
}

interface AppConsultationsRouteChildren {
  AppConsultationsIdRoute: typeof AppConsultationsIdRoute
  AppConsultationsRequestRoute: typeof AppConsultationsRequestRoute
}

const AppConsultationsRouteChildren: AppConsultationsRouteChildren = {
  AppConsultationsIdRoute: AppConsultationsIdRoute,
  AppConsultationsRequestRoute: AppConsultationsRequestRoute,
}

const AppConsultationsRouteWithChildren =
  AppConsultationsRoute._addFileChildren(AppConsultationsRouteChildren)

interface AppDashboardRouteChildren {
  AppDashboardCommunityRoute: typeof AppDashboardCommunityRoute
}

const AppDashboardRouteChildren: AppDashboardRouteChildren = {
  AppDashboardCommunityRoute: AppDashboardCommunityRoute,
}

const AppDashboardRouteWithChildren = AppDashboardRoute._addFileChildren(
  AppDashboardRouteChildren,
)

interface AppPatientRouteChildren {
  AppPatientMedicationsRoute: typeof AppPatientMedicationsRoute
  AppPatientRecordRoute: typeof AppPatientRecordRoute
  AppPatientScanRoute: typeof AppPatientScanRoute
}

const AppPatientRouteChildren: AppPatientRouteChildren = {
  AppPatientMedicationsRoute: AppPatientMedicationsRoute,
  AppPatientRecordRoute: AppPatientRecordRoute,
  AppPatientScanRoute: AppPatientScanRoute,
}

const AppPatientRouteWithChildren = AppPatientRoute._addFileChildren(
  AppPatientRouteChildren,
)

interface AppRouteChildren {
  AppAuditRoute: typeof AppAuditRoute
  AppCalculatorRoute: typeof AppCalculatorRoute
  AppConsultationsRoute: typeof AppConsultationsRouteWithChildren
  AppDashboardRoute: typeof AppDashboardRouteWithChildren
  AppDocumentRoute: typeof AppDocumentRoute
  AppFaqRoute: typeof AppFaqRoute
  AppHelpRoute: typeof AppHelpRoute
  AppMaternalRoute: typeof AppMaternalRoute
  AppNotificationsRoute: typeof AppNotificationsRoute
  AppPatientRoute: typeof AppPatientRouteWithChildren
  AppReferralsRoute: typeof AppReferralsRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppSupervisorRoute: typeof AppSupervisorRoute
  AppTriageRoute: typeof AppTriageRoute
  AppPatientsPatientIdRoute: typeof AppPatientsPatientIdRoute
  AppPatientsBatchRegisterRoute: typeof AppPatientsBatchRegisterRoute
  AppPatientsIndexRoute: typeof AppPatientsIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAuditRoute: AppAuditRoute,
  AppCalculatorRoute: AppCalculatorRoute,
  AppConsultationsRoute: AppConsultationsRouteWithChildren,
  AppDashboardRoute: AppDashboardRouteWithChildren,
  AppDocumentRoute: AppDocumentRoute,
  AppFaqRoute: AppFaqRoute,
  AppHelpRoute: AppHelpRoute,
  AppMaternalRoute: AppMaternalRoute,
  AppNotificationsRoute: AppNotificationsRoute,
  AppPatientRoute: AppPatientRouteWithChildren,
  AppReferralsRoute: AppReferralsRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppSupervisorRoute: AppSupervisorRoute,
  AppTriageRoute: AppTriageRoute,
  AppPatientsPatientIdRoute: AppPatientsPatientIdRoute,
  AppPatientsBatchRegisterRoute: AppPatientsBatchRegisterRoute,
  AppPatientsIndexRoute: AppPatientsIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
